InseeFrLab/helm-charts-interactive-services

charts/jupyter-pyspark-gpu/Chart.yaml
charts/jupyter-pyspark/Chart.yaml
charts/jupyter-python-gpu/Chart.yaml
charts/jupyter-python/Chart.yaml
charts/jupyter-pytorch-gpu/Chart.yaml
charts/jupyter-pytorch/Chart.yaml
charts/jupyter-r/Chart.yaml
charts/jupyter-tensorflow-gpu/Chart.yaml
charts/jupyter-tensorflow/Chart.yaml
charts/vscode-python-gpu/Chart.yaml
charts/vscode-python/Chart.yaml
charts/vscode-pytorch-gpu/Chart.yaml
charts/vscode-pytorch/Chart.yaml
charts/vscode-tensorflow-gpu/Chart.yaml
charts/vscode-tensorflow/Chart.yaml

This is to allow library-chart to build a  1.1.0 release through the existing Github Action.
Right now, this fails because said Github Action first tries to build jupyter-pyspark, which depends on library-chart:1.1.0, which does not exist yet.

Downgrade dependency to library-chart (1.1.0 -> 1.0.3)

---

charts/jupyter-pyspark-gpu/Chart.yaml
charts/jupyter-pyspark/Chart.yaml
charts/jupyter-python-gpu/Chart.yaml
charts/jupyter-python/Chart.yaml
charts/jupyter-pytorch-gpu/Chart.yaml
charts/jupyter-pytorch/Chart.yaml
charts/jupyter-r/Chart.yaml
charts/jupyter-tensorflow-gpu/Chart.yaml
charts/jupyter-tensorflow/Chart.yaml
charts/rstudio-gpu/Chart.yaml
charts/rstudio-sparkr/Chart.yaml
charts/rstudio/Chart.yaml
charts/vscode-python-gpu/Chart.yaml
charts/vscode-python/Chart.yaml
charts/vscode-pytorch-gpu/Chart.yaml
charts/vscode-pytorch/Chart.yaml
charts/vscode-tensorflow-gpu/Chart.yaml
charts/vscode-tensorflow/Chart.yaml

This was the intended version for https://github.com/InseeFrLab/helm-charts-interactive-services/pull/18, but we had to roll that back in order to *first* be able to build `library-chart` v1.1.0.

Bump dependency to library-chart v1.1.0

---

charts/jupyter-pyspark-gpu/Chart.yaml
charts/jupyter-pyspark/Chart.yaml
charts/jupyter-python-gpu/Chart.yaml
charts/jupyter-python/Chart.yaml
charts/jupyter-pytorch-gpu/Chart.yaml
charts/jupyter-pytorch/Chart.yaml
charts/jupyter-r/Chart.yaml
charts/jupyter-tensorflow-gpu/Chart.yaml
charts/jupyter-tensorflow/Chart.yaml
charts/rstudio-gpu/Chart.yaml
charts/rstudio-sparkr/Chart.yaml
charts/rstudio/Chart.yaml
charts/vscode-python-gpu/Chart.yaml
charts/vscode-python/Chart.yaml
charts/vscode-pytorch-gpu/Chart.yaml
charts/vscode-pytorch/Chart.yaml
charts/vscode-tensorflow-gpu/Chart.yaml
charts/vscode-tensorflow/Chart.yaml

Hopefully this is the last one. Summary of the trials and tribulations : 
- https://github.com/InseeFrLab/helm-charts-interactive-services/pull/18 bumped all the charts versions (library-charts + the various IDEs), which caused the `release` Github Action to fail : the IDE charts had a dependency on a version of `library-chart` which was not built.
- https://github.com/InseeFrLab/helm-charts-interactive-services/pull/21 then downgraded the IDE charts' dependency to `library-chart`, in order to allow building the new version for `library-chart` itself (v 1.1.0)... but this also built the IDE charts with their new version from #18
- https://github.com/InseeFrLab/helm-charts-interactive-services/pull/22 was intended to rebuild the IDE charts with the proper version for `library-charts` …

Bump chart version by 0.0.1 to allow rebuild

---

charts/children.yaml
charts/rstudio-gpu/Chart.yaml
charts/rstudio-gpu/values.schema.json
charts/rstudio/Chart.yaml
charts/rstudio/values.schema.json

Hello,
Quick PR to suggest a correction on the various version enums in the `value.schema.json` files for `rstudio` and `rstudio-gpu`.
I removed the `ds-` part (which seems to have disappeared), and also *downgraded* the version - this seems counterintuitive, but I just followed the tags visible here : https://hub.docker.com/r/inseefrlab/onyxia-rstudio/tags.
Might have missed something though, in which case, thanks for telling me where. :)

[RStudio] Update the version enums (remove 'ds-' + downgrade)

---

charts/jupyter-pyspark/Chart.yaml
charts/jupyter-pyspark/templates/statefulset.yaml
charts/rstudio-sparkr/Chart.yaml
charts/rstudio-sparkr/templates/statefulset.yaml

After tripping on this per chance, here's a quick PR to add some conditionals in the stateful set template of two different charts. To be precise : 
- jupyter-spark : added `{{- if .Values.s3.enabled }}` twice to condition the "core site" config map
- rstudio-sparkr : same as abobe + added `{{- if .Values.spark.default }}` once to condition the "spark conf" config map
These checks are already present in `library-chart` ([see here for instance](https://github.com/InseeFrLab/helm-charts-interactive-services/blob/2dfb75622d8a54162bdd8b039efafc5fc90090b2/charts/library-chart/templates/_configmap.tpl#L187))

Add missing checks for config maps in stateful set template

---

charts/library-chart/Chart.yaml
charts/library-chart/templates/_configmap.tpl

*This PR is a replacement for #49, which I sabotaged with a bad rebase - I'll just copy the description from that one below.*
---
Spark workloads may require the download of third-party Java dependencies (eg : PostgreSQL JDBC driver).
This PR is part one of a set of changes aiming at allowing an end-user to configure a specific Maven repository for such dependency resolution, instead of using the default (Maven Central) - which is not usable in offline environments.
This first part focuses on `library-chart` only, the second will update the actual Spark based charts (jupyter-pyspark, jupyter-pyspark-gpu and rstudio-sparkr).
For some implementation details : 
- Spark uses Ivy for dependency resolution, and two parameters to change this, `spark.jars.ivySettings` and …

library-chart : add CM for ivysettings.xml

---

charts/rstudio-gpu/Chart.yaml
charts/rstudio-gpu/README.md
charts/rstudio-gpu/values.schema.json
charts/rstudio-gpu/values.yaml
charts/rstudio-sparkr/Chart.yaml
charts/rstudio-sparkr/README.md
charts/rstudio-sparkr/values.schema.json
charts/rstudio-sparkr/values.yaml
charts/rstudio/Chart.yaml
charts/rstudio/README.md
charts/rstudio/values.schema.json
charts/rstudio/values.yaml

This actually contains the changes pushed in https://github.com/InseeFrLab/helm-charts-interactive-services/pull/76, but that one should be merged first, to allow the proper rebuild of library-chart with its new version. I'll rebase if Github finds a conflict. As such, leaving this as draft for now.
The change itself is mostly centered on the `values.schema.json` files to make use of `packageRepositoryInjection` and set the `repository.packageManagerUrl` parameter accordingly. This parameter (or rather, the environment variable it sets) is unused for now, I'll make another PR on the https://github.com/InseeFrLab/images-datascience repo for that.

Use `packageManagerUrl` from Onyxia region when available

---

renovate.json

- Added `bumpVersion` in the renovate.json.
- When renovate did a MR, the chart version was not implemented in Chart.yaml. With this parameter it will be bumped
See reference [in the official documentation](https://docs.renovatebot.com/configuration-options/#bumpversion) and an example that works here:

added bumpVersion to renovate

---

charts/rstudio-sparkr/Chart.yaml
charts/rstudio-sparkr/README.md
charts/rstudio-sparkr/templates/statefulset.yaml
charts/rstudio-sparkr/values.yaml

Currently, the `make-secrets-writable` initContainer, and the "main" container in `rstudio-sparkr` Chart share the same security context. As the RStudio image needs to runAsRoot to work properly, this implies the initContainer image also runs as root, even though it's not strictly necessary.
This PR changes the StatefulSet template to have a dedicated parameter for the initContainer's security context, to allow reducing the privileges for the initContainer.
Ping @alexisdondon to make sure this is enough, and any other maintainer to review and check if this is acceptable.

RStudio Sparkr : split container and initContainer securityContext

---

charts/library-chart/Chart.yaml
charts/library-chart/templates/_role_binding.tpl

Add openshift compatibilty for helm charts repositories. 
- `charts/library-chart/` : add rolebindings with scc

feat: :sparkles: ocp compatibility library chart

---

tests/deployment_test.yaml

Provides a dummy secret in unittest's kubernetesProvider to avoid a known bug coming from empty lookups
https://github.com/helm-unittest/helm-unittest/issues/380

Dummy secret in unittest's kubernetesProvider

---

charts/jupyter-pyspark/Chart.yaml
charts/jupyter-pyspark/values.schema.json
charts/jupyter-pyspark/values.yaml
charts/jupyter-python/Chart.yaml
charts/jupyter-python/values.schema.json
charts/jupyter-python/values.yaml
charts/vscode-pyspark/Chart.yaml
charts/vscode-pyspark/values.schema.json
charts/vscode-pyspark/values.yaml
charts/vscode-python/Chart.yaml
charts/vscode-python/values.schema.json
charts/vscode-python/values.yaml

All Python-based charts now use the new Python 3.12.5 images (soon to be published).

[Python version update] Charts use the new python 3.12.5 images

---

charts/library-chart/Chart.yaml
charts/library-chart/templates/_secret.tpl

Partial rollback of https://github.com/InseeFrLab/helm-charts-interactive-services/commit/54f219505ddd37717e35b988daea46f9195f9d54#diff-aa92606069b7c34b1dd15e3161a4fe088432100935d45c9677b64f5a38efd2daR397
While keeping the new test using `.Values.proxy.enabled` instead of `.Values.proxy`, add back the old $NO_PROXY based value for `-Dhttp.nonProxyHosts` and `-Dhttps.nonProxyHosts`

[library-chart] Partial rollback of Spark proxy exceptions

---

charts/jupyter-pyspark/Chart.yaml
charts/rstudio-sparkr/Chart.yaml
charts/vscode-pyspark/Chart.yaml

Bump library-chart for Spark-based charts to fix nonProxyHosts config (see #162). Scope : 
- jupyter-pyspark
- rstudio-sparkr
- vscode-pyspark

[spark based charts] Bump library-chart to fix nonProxyHosts config

---

charts/library-chart/Chart.yaml
charts/library-chart/templates/_ingress.tpl

Add `useTlsSecret` variable to allow users to use the secretName in ingress tls without having to set "useCertManager" variable to true
- [ x] Chart version bumped in `Chart.yaml`
- [ x] Title of the pull request follows this pattern [name_of_the_chart] Descriptive title

[library-chart] modify condition on ingress tls secretName

---

charts/jupyter-pyspark/Chart.yaml
charts/jupyter-pyspark/values.schema.json
charts/jupyter-pyspark/values.yaml
charts/jupyter-python/Chart.yaml
charts/jupyter-python/values.schema.json
charts/jupyter-python/values.yaml
charts/rstudio-sparkr/Chart.yaml
charts/rstudio-sparkr/values.schema.json
charts/rstudio-sparkr/values.yaml
charts/rstudio/Chart.yaml
charts/rstudio/values.schema.json
charts/rstudio/values.yaml
charts/vscode-pyspark/Chart.yaml
charts/vscode-pyspark/values.schema.json
charts/vscode-pyspark/values.yaml
charts/vscode-python/Chart.yaml
charts/vscode-python/values.schema.json
charts/vscode-python/values.yaml

Add default value for ingress.useTlsSecret in all charts & upgrade to library-chart 1.5.27 due to #166 
- [x ] Chart version bumped in `Chart.yaml`
- [ x] Title of the pull request follows this pattern [name_of_the_chart] Descriptive title

[All] add default value ingress.usetlssecret

---

charts/jupyter-pyspark/Chart.yaml
charts/jupyter-pyspark/templates/NOTES.txt
charts/jupyter-pyspark/values.schema.json
charts/jupyter-pyspark/values.yaml
charts/jupyter-python/Chart.yaml
charts/jupyter-python/templates/NOTES.txt
charts/jupyter-python/values.schema.json
charts/jupyter-python/values.yaml
charts/rstudio-sparkr/Chart.yaml
charts/rstudio-sparkr/templates/NOTES.txt
charts/rstudio-sparkr/values.schema.json
charts/rstudio-sparkr/values.yaml
charts/rstudio/Chart.yaml
charts/rstudio/templates/NOTES.txt
charts/rstudio/values.schema.json
charts/rstudio/values.yaml
charts/vscode-pyspark/Chart.yaml
charts/vscode-pyspark/templates/NOTES.txt
charts/vscode-pyspark/values.schema.json
charts/vscode-pyspark/values.yaml
charts/vscode-python/Chart.yaml
charts/vscode-python/templates/NOTES.txt
charts/vscode-python/values.schema.json
charts/vscode-python/values.yaml

[ALL] #173 Expose multiple custom user-specified ports

---

charts/jupyter-pyspark/Chart.yaml
charts/jupyter-pyspark/templates/statefulset.yaml
charts/jupyter-pyspark/values.schema.json
charts/jupyter-pyspark/values.yaml
charts/jupyter-python/Chart.yaml
charts/jupyter-python/templates/statefulset.yaml
charts/jupyter-python/values.schema.json
charts/jupyter-python/values.yaml
charts/vscode-pyspark/Chart.yaml
charts/vscode-pyspark/templates/statefulset.yaml
charts/vscode-pyspark/values.schema.json
charts/vscode-pyspark/values.yaml
charts/vscode-python/Chart.yaml
charts/vscode-python/templates/statefulset.yaml
charts/vscode-python/values.schema.json
charts/vscode-python/values.yaml

Add an environment variable in order to not activate the default conda env.

[Vscode-Jupyter] add custom python env variable

---

charts/library-chart/Chart.yaml
charts/library-chart/templates/_secret.tpl

bump to 1.6.0 and Adding 2 new keys into S3 secret AWS_WORKING_DIRECTORY_PATH and  AWS_PATH_STYLE_ACCES
- [X ] Chart version bumped in `Chart.yaml`
- [X ] Title of the pull request follows this pattern [name_of_the_chart] Descriptive title

[librairy Chart] Adding 2 new keys into S3 secret 

---

charts/jupyter-pyspark/Chart.yaml
charts/jupyter-pyspark/README.md
charts/jupyter-pyspark/templates/statefulset.yaml
charts/jupyter-pyspark/values.schema.json
charts/jupyter-python/Chart.yaml
charts/jupyter-python/README.md
charts/jupyter-python/templates/statefulset.yaml
charts/jupyter-python/values.schema.json
charts/jupyter-r-python-julia/README.md
charts/jupyter-r-python-julia/templates/statefulset.yaml
charts/jupyter-r-python-julia/values.schema.json
charts/jupyter-r-python-julia/values.yaml
charts/rstudio-sparkr/Chart.yaml
charts/rstudio-sparkr/README.md
charts/rstudio-sparkr/templates/statefulset.yaml
charts/rstudio-sparkr/values.schema.json
charts/rstudio-sparkr/values.yaml
charts/rstudio/Chart.yaml
charts/rstudio/README.md
charts/rstudio/values.schema.json
charts/rstudio/values.yaml
charts/vscode-pyspark/Chart.yaml
charts/vscode-pyspark/README.md
charts/vscode-pyspark/templates/statefulset.yaml
charts/vscode-pyspark/values.schema.json
charts/vscode-python/Chart.yaml
charts/vscode-python/README.md
charts/vscode-python/templates/statefulset.yaml
charts/vscode-python/values.schema.json

See https://github.com/InseeFrLab/images-datascience/pull/245

Adapt charts to new images

---

charts/jupyter-pyspark/Chart.yaml
charts/jupyter-pyspark/values.schema.json
charts/jupyter-pyspark/values.yaml
charts/jupyter-python/Chart.yaml
charts/jupyter-python/values.schema.json
charts/jupyter-python/values.yaml
charts/rstudio-sparkr/Chart.yaml
charts/rstudio-sparkr/values.schema.json
charts/rstudio-sparkr/values.yaml
charts/rstudio/Chart.yaml
charts/rstudio/values.schema.json
charts/rstudio/values.yaml
charts/vscode-pyspark/Chart.yaml
charts/vscode-pyspark/values.schema.json
charts/vscode-pyspark/values.yaml
charts/vscode-python/Chart.yaml
charts/vscode-python/values.schema.json
charts/vscode-python/values.yaml

[All] Allow custom Tls secret name

---

utils/charts-inheritance.yaml

Chart helm rstudio-r-python-julia added to catalog. 
Minor version upgrade to R4.5.1 for r-python-julia images.

[rstudio-r-python-julia] Add to catalog

---

charts/library-chart/Chart.yaml
charts/library-chart/templates/_ingress.tpl
charts/library-chart/templates/_route.tpl

Following https://github.com/InseeFrLab/onyxia/issues/996 in the aim of making Onyxia able -for some services- to handle path-type URL instead of sub-domain, we're trying to override dynamically inject the path in the ide/ingress.json (https://github.com/InseeFrLab/onyxia-api/blob/b47eece8103fa6bc78302390b3f0b8570de9e494/onyxia-api/src/main/resources/schemas/ide/ingress.json#L31).
However since the variable does not exists in your charts i believe it will not work prior to this change.

[library-chart] Add support for Path type override
